### ISSUE TITLE
Password prompt and spinner not centered

### ISSUE THREAD

**Issue by dmark04** [jtyr/plymouth-theme-arch-breeze#3]
Just installed this theme and for me the spinner on shutting down is really off-centered (shifted to the bottom right). The password prompt on login is centered at first, but if press Esc once it also moves to the totally off-centered position on the bottom right.
Is there any way to fix this manually ? (e.g. adjusting display resolution somewhere?)

**Comment by jtyr** [comment]
Position of every element is calculated from the screen resolution. What resolution do you use? Do you use any scaling?

**Comment by dmark04** [comment]
I'm on systemd-boot using the automatic display resolution (display-mode auto). I tried playing around with that a bit but it doesn't change anything (for the theme).
What I don't understand is how the display resolution would be different on shutdown than on boot? (aka. why is the position of the element off-centered only on shutdown while on boot it is fine?)
Also if the position of *every* element is calculated from screen resolution, why is the logo still centered and just the spinner element off?

Edit: I haven't managed to reproduce the off-centered password prompt reliably.

**Comment by dmark04** [comment]
After updating some system packages today, the issue fixed itself. If I find out what did it in the end i will update here.
